kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: tkb # Cluster name
networking:
  ipFamily: dual # Enable IPv4 and IPv6 networking
nodes:
- role: control-plane
  image: kindest/node:v1.29.0 # Find the latest image versions on Docker Hub
- role: worker # under the 'kindest/node' repo
  image: kindest/node:v1.29.0
- role: worker
  image: kindest/node:v1.29.0
- role: worker
  image: kindest/node:v1.29.0
